# Generated by Django 3.0.3 on 2020-02-23 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='path',
            name='color',
            field=models.CharField(default='black', max_length=128),
        ),
        migrations.AddField(
            model_name='point',
            name='x',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='point',
            name='y',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
