# Generated by Django 3.0.3 on 2020-02-25 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20200223_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='version',
            field=models.IntegerField(default=0),
        ),
    ]
